- name: install nginx
  hosts: web
  become: yes
  tasks: 
  - name: install nginx and run
    ansible.builtin.package:
      name: Nginx
      state: present

  - name: service to run
    ansible.builtin.service:
      name: Nginx
      state: started
      enabled: yes