- name: install nginix
  hosts: web
  become: yes
  tasks: 
  - name: install nginx and run
    ansible.builtin.package:
      name: nginx
      state: present
  - name: nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes