- name: install httpd
  hosts: web
  become: true
  tasks: 
  - name: install httpd
    ansible.builtin.package:
      name: httpd
      state: latest

  - name: apace service to run
    ansible.builtin.service:
      name: httpd
      state: started
      enabled: true