- name: install httpd
  hosts: web
  become: true
  tasks: 
  - name: install httpd and run
    ansible.builtin.package:
      name: httpd
      state: started

  - name: apace service to run
    ansible.builtin.service:
      name: httpd
      state: reloaded
      enabled: yes