- name: variables to print
  hosts: web
  vars:
    Course: "Devops with AWS"
    Duration: "120HRS"
    Learner: "Hari"
  tasks:
  - name: print the message
    ansible.builtin.debug:
      mess: "COURSE {{Course}}, DURATION{{Duration}}, LEARNER{{Learner}}"