- name: variables to print
  hosts: web
  # vars:
  #   Course: "Devops with AWS"
  #   Duration: "120HRS"
  #   Learner: "Hari"
  tasks:
  - name: print the message
    ansible.builtin.debug:
    # meg: "COURSE {{Course}}, DURATION  is :{{Duration}}, LEARNER is :{{Learner}}"
      # meg: "COURSE is {{Course}}, DURATION  is{ {Duration}},  LEARNER is :{{Learner}}""