- name : check the conditional
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: enter the number


  tasks:
  - name: print the number less than 10
    ansible.builtin.debug:
     msg: "print  the{{my_number}}  less than 10"
    when: number  | int <10


  - name: print the number grater than 10
    ansible.builtin.debug:
      msg: "print  the{{my_number}}  grater than 10"
    when: my_number | int >10



