- name : check the conditional
  hosts: local
  connection: localhost
  vars_promt:
  - name: "number"
    prompt: enter the number


  tasks:
  - name: print the number less than 10
    ansible.builtin.debug:
     msg: "print  the{{number}}  less than 10"
    when: number <10


  - name: print the number grater than 10
    ansible.builtin.debug:
      msg: "print  the{{number}}  grater than 10"
    when: number >10



