- name: to check the number is less that 10
  hosts: local
  connection: local
  vars_prompt:
  - name: my_number
    prompt: enter the number
    private: false

  tasks:
  - name: print the number less than 10
    ansible.builtin.debug:
      msg: "hi number {{my_number}} is less than 10"
    when: my_number | int < 10

  - name: print the number greather than 10
    ansible.builtin.debug:
      msg: "hi number{{my_number}} is grather than 10"
    when: my_number | int >  10