- name: loop demo
  hosts: web
  connection: local
  tasks: 
  - name: the loop to print
    ansible.builtin.debug:
     msg: " Hello {{item}}"  # ansible_default key to values in loop
    loop:
    - Ramesh
    - Raju
    - Balu
    - srinu
