- name: the loop packages to install
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Packages to install
    ansible.builtin.package:
      name: "{{item}}"
      state: present

    loop:
    - ngnix
    - mysql
    - httpd
    - apache2
