- name: the loop packages to install
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Packages to install
    ansible.builtin.package:
      msg: "the packages are :{{item}}" # default key for loops

    loop:
    - ngnix
    - mysql
    - httpd
    - apache2
