- name: the loop packages to install
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: Packages to install
    ansible.builtin.package:
      name: "{{item}}"   # iteam is reserve ward for using for loop
      state: present

    loop:
    - nginx
    - mysql
    - httpd
    - apache2
