- name: the package to install and uninstall via loop
  hosts: local
  connection: local
  tasks:
  - name: the packages to install
    ansible.builtin.package:
      name: "{{item.name}}"
      state: "{{item.state}}"

    loop:
    - {name: 'nginx' ,state: 'present'}
    - {name: 'httpd' ,state: 'absent'}
    - {name: postfix, state: 'present'}
    - {name: 'mysql', state: 'absent'}



