- name: the package to install and uninstall via loop
  hosts: local
  connection: local

  tasks:
  - name: the packages to install
    ansible.builtin.packages:
      name: "{{item.name}}"
      state: "{{item.state}}"
    loop:
    - {name: 'ngnix' ,state: 'present'}
    - {name: 'httpd' ,state: 'absent'}
    - {name: postfix, state: 'present'}
    - {name: 'mysql', state: 'absent'}



